import './globals.css';

import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
} from 'next/font/google';
import Link from 'next/link';

import { Toaster } from '@/components/ui/Sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-6 sticky top-0 bg-white border-b shadow-md z-50">
          <nav>
            <ul className="flex gap-4 text-lg">
              <li>
                <Link href={`/`}>Products</Link>
              </li>
              <li>
                <Link href={`/wishlist`}>Wishlists</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="min-h-full container mx-auto py-8 grid gap-4 content-start">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
